# Generated by Django 5.0 on 2024-01-31 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0003_itemmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmodel',
            old_name='description',
            new_name='ingree',
        ),
        migrations.RenameField(
            model_name='itemmodel',
            old_name='price',
            new_name='step',
        ),
    ]
