# Generated by Django 5.0 on 2024-01-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0004_rename_description_itemmodel_ingree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='image',
            field=models.ImageField(upload_to='rsapp/static'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='step',
            field=models.CharField(max_length=1000),
        ),
    ]
