# Generated by Django 5.0 on 2024-02-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0006_alter_itemmodel_ingree_alter_itemmodel_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='image',
            field=models.ImageField(upload_to='rsapp/static/images'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='ingree',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='step',
            field=models.CharField(max_length=1200),
        ),
    ]
