# Generated by Django 5.0 on 2024-02-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0007_alter_itemmodel_image_alter_itemmodel_ingree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='image',
            field=models.ImageField(upload_to='rsapp/static'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='ingree',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='step',
            field=models.CharField(max_length=3000),
        ),
    ]
