# Generated by Django 5.0 on 2024-02-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0008_alter_itemmodel_image_alter_itemmodel_ingree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
