# Generated by Django 5.0 on 2024-02-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
