# Generated by Django 5.0 on 2024-02-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0011_itemmodel_type_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='review_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=10)),
                ('comment', models.CharField(max_length=50)),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
