# Generated by Django 5.0 on 2024-02-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsapp', '0012_review_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_model',
            name='name',
            field=models.CharField(default=6, max_length=20),
            preserve_default=False,
        ),
    ]
